name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    # For a list of available runner types, refer to
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: windows-latest
    
    env:
      name: app-win
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release -r win-x64 --no-restore
    
    - name: Publish
      run: dotnet publish -c Release -o ${{ github.workspace }}/artifact --no-build -r win-x64
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:	
        name: ${{ env.name }}
        path: ${{ github.workspace }}/artifact/**/*
